### ISSUE TITLE
Implement user's credentials' storage solution

### ISSUE THREAD

**Issue by groovytron** [j4kim/Flan411#3]
Use either configuration file or binary format registry. If possible, a minimum of security features could be nice but let's keep it simple at first.

**Comment by j4kim** [comment]
Done in the console application https://github.com/j4kim/Flan411/commit/f9acf948ff817bb0c0eba5d26dba24b36c18af5e
and with a simple file `.token` in the executables directory

**Comment by groovytron** [comment]
I'll make the UI use your work tomorrow. Good job! 👍

**Comment by groovytron** [comment]
Implemented in the UI here: b02677030b8befef56de320d7959705dcd00b685
